### ISSUE TITLE
Tool for constructing uncertainty vs signal ROI size needed.

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-toolkit#168]
# Signal uncertainty

**Signal uncertainty** is defined as the average "signal" waveform amplitude per sample (tick) in a reconstructed signal-ROI of a given size and when the input to the signal processing consists only of noise.

The signal uncertainty thus is a function of the signal-ROI size as well as the choice of noise model (or in principle real detector data, if contribution from ionization electrons can be excluded).

# Procedure

In the somewhat distant past a dedicated study was performed to produce MicroBooNE's signal uncertainty vs ROI size table.  This needs to be replicated in the form of a general purpose, multi-detector tool.

Here is the procedure:

1) Input: ADC waveforms from noise on per plane basis. 

2) Apply the usual 2D deconvolution from the signal processing resulting in both Wiener and Gaussian filtered waveforms.

3) Select a ROI window of given size and location.

4) Apply adaptive baseline correction to the waveform, over the ROI.

5) Sum the resulting signal.

6) Repeat multiple times for different ROI sizes and locations.

7) Calculate RMS of sum over locations as a function of ROI size.

8) Assign RMS as the signal uncertainty for the given ROI.

9) Interpolate between ROI sizes as needed.

# Variance 

Besides as a function of ROI window size, signal uncertainty may vary based on the noise:

- type of noise (eg, intrinsic w/ or w/out coherent)
- noise model parameters
- plane
- wire length

# Tasks

Some things known to be needed for this tool:

- [ ] Make (or figure how to make) SigProc output full waveforms w/out ROIs (decon only).
- [ ] Make configuration with pure-noise sim + decon + procedure.
  - use new "layers" config to provide detector independence
  - have NF TLA-optional
  - have optional TLA to set what noise to use
- [ ] Develop a new component to enact the procedure
  - directly produce a data file, eg as an `ITerminal`
- [ ] Develop component to load this data file and produce an "uncertainty frame" consistent with existing usage in `MaskSlices`.
- [ ] Validation to include:
  - reproduction of MB's table
  - plots of mean signal and signal uncertainty as a function of ROI window size
